# Generated by Django 5.0.7 on 2024-08-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disliked_comments_id',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_comments_id',
            field=models.JSONField(default=list),
        ),
    ]
