# Generated by Django 5.0.7 on 2024-09-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
