# Generated by Django 5.0.7 on 2024-08-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
