# Generated by Django 5.0.7 on 2024-09-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllNewsURLs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
