# Generated by Django 5.0.7 on 2024-07-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='comments',
            field=models.ManyToManyField(to='news.comment'),
        ),
    ]
