# Generated by Django 5.0.7 on 2024-08-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='payment_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='donate',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
