# Generated by Django 5.0.7 on 2024-08-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_donate_payment_id_donate_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='status',
        ),
    ]
