# Generated by Django 5.0.7 on 2024-08-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_remove_donate_payment_id_remove_donate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='payment_id',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='donate',
            name='status',
            field=models.CharField(default=''),
        ),
    ]
